on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Terraform-Lint
      uses: actionshub/terraform-lint@1.0.0
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@v1
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
